extends: [
  airbnb
]
parser: babel-eslint
env: {
  es6: true,
  browser: true,
  node: true
}
rules:
  indent:
    - error
    - 2
  max-len:
    - error
    - 120
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-unused-expressions:
    - off
  no-unused-vars:
    - warn
  no-plusplus:
    - off
  react/no-multi-comp:
    - off
  react/prop-types:
    - warn
  jsx-a11y/no-static-element-interactions:
    - off
  jsx-a11y/click-events-have-key-events:
    - off
plugins: [
  react,
  jsx-a11y,
  import
]
